version: "3.8"

services:
    # back0:
    #     build: .
    #     command: yarn app
    #     volumes:
    #         - .:/usr/app/
    #         - /usr/app/node_modules
    #     ports:
    #         - "9000:9000"
    #     environment:
    #         - NEW_RELIC_LICENSE_KEY=eu01xx0ade2df0d71fd01ec7782eb808FFFFNRAL
    #         - NEW_RELIC_APP_NAME=testing-apm-0
    #         - NEW_RELIC_RECORD_SQL=obfuscated
    #         - SOMETHING_URL=http://back1:9000/somethings
    #         - PORT=9000
    #         - NODE_ENV=localhost
    #         - DATABASE__DRIVER=mysql2
    #         - DATABASE__HOST=db-mysql
    #         - DATABASE__DATABASE=db
    #         - DATABASE__USER=user
    #         - DATABASE__PASSWORD=password
    #         - DATABASE__PORT=3306
    #         - DATABASE__POOL_MIN=5
    #         - DATABASE__POOL_MAX=20
    #         - RABBITMQ_URL=amqp://rabbitmq
    #         - TZ=Asia/Bangkok

    # back1:
    #     build: .
    #     command: yarn app
    #     volumes:
    #         - .:/usr/app/
    #         - /usr/app/node_modules
    #     ports:
    #         - "9001:9001"
    #     environment:
    #         - NEW_RELIC_LICENSE_KEY=eu01xx0ade2df0d71fd01ec7782eb808FFFFNRAL
    #         - NEW_RELIC_APP_NAME=testing-apm-1
    #         - NEW_RELIC_RECORD_SQL=obfuscated
    #         - SOMETHING_URL=http://back0:9000/somethings
    #         - PORT=9001
    #         - NODE_ENV=localhost
    #         - DATABASE__DRIVER=mysql2
    #         - DATABASE__HOST=db-mysql
    #         - DATABASE__DATABASE=db
    #         - DATABASE__USER=user
    #         - DATABASE__PASSWORD=password
    #         - DATABASE__PORT=3306
    #         - DATABASE__POOL_MIN=5
    #         - DATABASE__POOL_MAX=20
    #         - RABBITMQ_URL=amqp://rabbitmq
    #         - TZ=Asia/Bangkok

    # db-mysql:
    #     image: mysql:8.0.31
    #     restart: always
    #     command: --default-authentication-plugin=mysql_native_password
    #     environment:
    #         MYSQL_DATABASE: "db"
    #         MYSQL_USER: "user"
    #         MYSQL_PASSWORD: "password"
    #         MYSQL_ROOT_PASSWORD: "password"
    #     ports:
    #         - "3306:3306"
    #     expose:
    #         - "3306"
    #     volumes:
    #         - my-db:/var/lib/mysql

    # db:
    #     image: postgres:14.1-alpine
    #     restart: always
    #     environment:
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     ports:
    #         - "5432:5432"
    #     volumes:
    #         - db:/var/lib/postgresql/data

    # rabbitmq:
    #     image: rabbitmq:3-management-alpine
    #     container_name: "rabbitmq"
    #     ports:
    #         - 5672:5672
    #         - 15672:15672
    #     volumes:
    #         - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
    #         - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

    redis:
        image: redis:alpine
        # environment:
        #     - REDIS_PASSWORD=secret
        #     - REDIS_USER=redis
        # command: /bin/sh -c "redis-server --requirepass $$REDIS_HOST_PASSWORD"
        env_file:
            - redis.env
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data

volumes:
    db:
        driver: local
    my-db:
    redis-data:
